<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="wsc-042" name="Test2" tests="9" failures="2" timestamp="23 Jan 2017 13:11:45 GMT" time="0.02" errors="0">
  <testcase name="checkDivisionNegative" time="0.001" classname="com.CalculatorTest.DivisionTest"/>
  <testcase name="checkDivisionPositive" time="0.001" classname="com.CalculatorTest.DivisionTest"/>
  <testcase name="checkDivisionPositiveNegative" time="0.0" classname="com.CalculatorTest.DivisionTest"/>
  <testcase name="checkDivisionSelf" time="0.001" classname="com.CalculatorTest.DivisionTest">
    <failure type="java.lang.AssertionError" message="10/10 operation result is wrong! expected [1.0] but found [10.0]">
      <![CDATA[java.lang.AssertionError: 10/10 operation result is wrong! expected [1.0] but found [10.0]
	at com.CalculatorTest.DivisionTest.checkDivisionSelf(DivisionTest.java:45)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- checkDivisionSelf -->
  <testcase name="checkMultiplicationFload" time="0.001" classname="com.CalculatorTest.MultiplicationTest"/>
  <testcase name="checkMultiplicationNegative" time="0.001" classname="com.CalculatorTest.MultiplicationTest"/>
  <testcase name="checkMultiplicationOne" time="0.001" classname="com.CalculatorTest.MultiplicationTest">
    <failure type="java.lang.AssertionError" message="10*1 operation result is wrong! expected [10.0] but found [1.0]">
      <![CDATA[java.lang.AssertionError: 10*1 operation result is wrong! expected [10.0] but found [1.0]
	at com.CalculatorTest.MultiplicationTest.checkMultiplicationOne(MultiplicationTest.java:44)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- checkMultiplicationOne -->
  <testcase name="checkMultiplicationPositive" time="0.001" classname="com.CalculatorTest.MultiplicationTest"/>
  <testcase name="checkMultiplicationZero" time="0.0" classname="com.CalculatorTest.MultiplicationTest"/>
</testsuite> <!-- Test2 -->
